<a href="https://colab.research.google.com/github/Hung-Ta-Chen/141A-final-project/blob/main/STA141a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import operator
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures
import seaborn as sns

In [2]:
#load data from google drive
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Mounted at /gdrive
/gdrive

In [17]:
path = '/gdrive/MyDrive/ufc_data.csv'
ufc_data = pd.read_csv(path)

In [18]:
ufc_data = ufc_data.drop(["R_fighter", "B_fighter", "Referee", "date", "location", "title_bout"], axis=1)
ufc_data = ufc_data.dropna()
display(ufc_data.shape)
ufc_data.head()

(3914, 138)

,Winner,weight_class,B_avg_KD,B_avg_opp_KD,B_avg_SIG_STR_pct,B_avg_opp_SIG_STR_pct,B_avg_TD_pct,B_avg_opp_TD_pct,B_avg_SUB_ATT,B_avg_opp_SUB_ATT,...,R_win_by_Decision_Unanimous,R_win_by_KO/TKO,R_win_by_Submission,R_win_by_TKO_Doctor_Stoppage,R_Stance,R_Height_cms,R_Reach_cms,R_Weight_lbs,B_age,R_age
0,Red,Bantamweight,0.000000,0.000,0.420000,0.495000,0.330000,0.360000,0.500000,1.0000,...,0,1,0,0,Orthodox,170.18,177.80,135.0,31.0,27.0
1,Red,Middleweight,0.500000,0.000,0.660000,0.305000,0.300000,0.500000,1.500000,0.0000,...,0,3,0,0,Orthodox,182.88,187.96,185.0,32.0,28.0
4,Blue,WomenBantamweight,0.125000,0.000,0.535625,0.578750,0.185000,0.166250,0.125000,0.1875,...,1,2,2,0,Orthodox,167.64,172.72,135.0,29.0,43.0
5,Blue,Lightweight,0.000000,0.000,0.515000,0.473750,0.435000,0.250000,1.250000,0.6250,...,2,2,2,0,Orthodox,182.88,190.50,155.0,27.0,41.0
6,Blue,Welterweight,0.046875,0.125,0.459277,0.404687,0.322188,0.068867,0.189453,0.0000,...,1,3,0,0,Orthodox,182.88,180.34,170.0,35.0,31.0